mozilla-releng/fxci-config

.github/workflows/deploy.yml

It turns out PRs can't access the env defined in the Github environment, so we need to dynamically write the proper value to the $GITHUB_ENV file instead.

ci: fix the deploy / check job on PRs

---

projects.yml

Two things were notice since https://bugzilla.mozilla.org/show_bug.cgi?id=1903776 landed:
* There is no testing branch in https://github.com/mozilla-releng/product-details
* https://hg.mozilla.org/try/ can be pushed to on any branch, so we should keep its * branch and drop the explicit reference to default
Already reviewed in https://phabricator.services.mozilla.com/D216274

Bug 1907300: adjust projects.yml branches to match reality

---

clients.yml

Add TC clients for autophone/bitbar a55 and s24 devices.
See https://mozilla-hub.atlassian.net/browse/RELOPS-883 and https://mozilla-hub.atlassian.net/browse/RELOPS-976.

add clients for bitbar/autophone a55 and s24 devices

---

.github/workflows/deploy.yml

Some improvements to the Slack message that the notify task runs.
Unfortunately I can't access the webhook url secret anymore (and I'm afraid if I revoke it, I won't be able to re-create it). So I haven't been able to it fully.. but I simulated creating the `SLACK_MESSAGE` variable locally and it looks like it should work.

ci: improve the look of notify job's Slack messages

---

clients.yml

Due to play store review delays, we're not scheduling the ship phase automatically (see
https://hg.mozilla.org/mozilla-central/rev/4bab23e5cf43).

Bug 1884740 - add promote_android scopes to gecko shipitscript

---

projects.yml

My understanding is that we don't want to run this directly on mozilla-central anymore. I just did by accident. Unless there's a reason to keep these, let's drop them.
Aryx points out that in an emergency we can run on autoland and graft to central.

bug 1907655: remove l10n bump cron task/hook from mozilla-central

---

.github/CODEOWNERS

https://github.com/mozilla-releng/fxci-config/pull/27 only added Releng to the review... but I thought it should add Releng and Relops.
This seems to be because CODEOWNERS evaulation uses the last matching rule for choosing reviewers (see https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners).

reorder codeowners

---

worker-images.yml
worker-pools.yml

Testing performed is mentioned in the first half of this change: https://phabricator.services.mozilla.com/D215274.
See https://mozilla-hub.atlassian.net/browse/RELOPS-988 and https://bugzilla.mozilla.org/show_bug.cgi?id=1902346 for more info.

Bug 1902346: no-scratch worker pools use image with updated livelog cert

---

worker-pools.yml

Our small test worked out well, and the cost is only marginally more than the US instances. Let's open up some more capacity here.
We're getting the GPU quota raised for this region in https://mozilla-hub.atlassian.net/browse/RELOPS-1011, so let's hold off merging this until that's dealt with, on the off chance we don't get the new limit we'd like.

bug 1907211: use europe-west4 instances in all preemptible translations GPU worker pools

---

projects.yml

Stage one of the plan written out in the bug.
This _should_ be quite safe. For Maple, all of the scopes that `branch:*` has are already granted by `branch:default`.
For GitHub we have some differences, but as far as I can tell, only where the explicit branches have more scopes than `branch:*` due to grants such as https://github.com/mozilla-releng/fxci-config/blob/944ea85da779ab430e932f9829f1f02bb11ee11c/grants.yml#L1185-L1200.
Original revision/discussion in https://phabricator.services.mozilla.com/D216239
`ci-admin diff` for this is in https://gist.github.com/bhearsum/61df6555dea05bebb9c12b491d6259ce

Bug 1907217: remove `*` branch from RelEng github repositories and `maple`

---

grants.yml
hooks.yml
hooks/project-relman/code-review-testing.yml

Refs https://github.com/mozilla/code-review/issues/2193
Needed for https://github.com/mozilla/code-review/pull/2235
The goal here is to use Taskcluster cache on the firefox-ci [code-review testing hook](https://firefox-ci-tc.services.mozilla.com/hooks/project-relman/code-review-testing) so that mercurial checkouts can be shared amongst tasks.
I'm not sure if I need to declare that scope in `grants.yml` for the hook or if it's assigned automatically.

Setup checkout cache for code review testing hook

---

grants.yml

builds moved from aws to gcp in bug 1757601, so we shouldn't be using s3 for sccache anymore.

Bug 1908850 - cleanup aws-s3 sccache grants

---

grants.yml
hooks.yml
hooks/project-relman/code-review-testing.yml

Followup https://github.com/mozilla-releng/fxci-config/pull/32#issuecomment-2238828444
This should fix the scope issue currently produced on [code-review-testing hook](https://firefox-ci-tc.services.mozilla.com/hooks/project-relman/code-review-testing) (sample [task](https://firefox-ci-tc.services.mozilla.com/tasks/H54Y9g22RlmSiXERiCazQw/runs/0/logs/public/logs/live.log)).

Use docker-worker cache for code-review testing hook

---

worker-pools.yml

[Bug 1908773: Create images-gcp-aarch64 pool to provision an appropiate instance type for image tasks](https://bugzilla.mozilla.org/show_bug.cgi?id=1908773)

Bug 1908773 - Create a L1 images-gcp-aarch64 worker pool

---

projects.yml

Removing the `*` branch from RelEng Github repos worked fine. `mozilla-vpn-client` is the next step for Github, which uses release promotion actions and is higher activity.
On the Mercurial side, we decided to keep the `*` branches since these will be going away sometime next year anyways, so I'm restoring it for `maple`.

bug 1907217: remove * branch from vpn repository; restore it for Maple 

---

projects.yml

This should've been done when `branches` was added.

fix: update projects.yml docstring about branches/levels

---

clients.yml
grants.yml
projects.yml

The new treestatus doesn't use taskcluster for auth.
Differential Revision: https://phabricator.services.mozilla.com/D216145

Bug 1903226 - remove treestatus project and grants.

---

worker-pools.yml

We're seeing out of disk issues in https://firefox-ci-tc.services.mozilla.com/tasks/DQeRyr1_TjmXhC0Z-5KWWw/runs/1, which is suspected to be an OpusTrainer bug. In the short term, we're going to workaround this by adding 2tb workers. In the medium term we'll fix the root cause and remove these.
Disks are pretty cheap (and certainly a tiny percentage of our translations spend), so while this is not ideal, it's not hugely expensive to do.

add 2tb gpu workers for translations

---

maintenance/pin.sh
pyproject.toml
taskcluster/docker/python/Dockerfile
taskcluster/kinds/docker-image/kind.yml
taskcluster/kinds/tests/kind.yml
tox.ini

Previously the Jenkins job was using Python 3.9, thus why we were running tests there. Now that we're using Github Actions to deploy, we should test against the same version that uses instead (3.11).

chore: drop support for Python 3.9

---

projects.yml

@kaya contacted me to request this change. 
I have verified that `https://hg.mozilla.org/projects/oak/json-repoinfo` reports scm_level_3.

change scm_level of oak project to 3

---

grants.yml

Reverts #56 (should no longer be needed)

Bug 1912260 - revert grants for Fenix beta builds on oak

---

grants.yml
src/ciadmin/check/check_hg_push_scopes.py

These have been obsolete for about 5 years.

Remove aws provisioner references

---

projects.yml

This depends on a handful of PRs to these repos:
https://github.com/mozilla-mobile/reference-browser/pull/2982
https://github.com/mozilla-mobile/firefox-ios/pull/21357
https://github.com/mozilla/code-review/pull/2289
https://github.com/mozilla/code-coverage/pull/2408
https://github.com/mozilla/firefox-translations-training/pull/777
https://github.com/mozilla-platform-ops/cloud-image-builder/pull/21
https://github.com/mozilla-releng/adhoc-signing/pull/213
https://github.com/mozilla-extensions/xpi-manifest/pull/235
After this change, the only Github repositories with `*` branches will be `staging` repositories, as was discussed in https://github.com/mozilla-releng/fxci-config/pull/18.

bug 1907217: remove * star branches from remaining github repositories

---

src/ciadmin/generate/tcyml.py

This fixes a rare race condition in in_tree_actions.py for projects with .taskcluster.yml files that differ by branch. (Most notably, tooltool has a branch with a .taskcluster.yml that is considered invalid, and causes us to sometimes generate _no_ action hooks for that repo.)

fix: cache tcyml files by url instead of repo path

---

worker-pools.yml

This pool can get highly backed up at times; let's bump the max capacity. This shouldn't affect cost at all, merely get things done sooner.

bump max capacity of t-linux-kvm-noscratch-gcp

---

clients.yml

This is going to be used in a task that runs `tc-admin diff` in fxci-config's CI.

ci: add client capable of generating the tc config

---

grants.yml
projects.yml

This cron job no longer exists, having been folded into firefox-android nightlies and releases.
While there, also remove grants for nightly cron job on archived mozilla-mobile projects.

Bug 1882100 - remove hooks and grants for ship-geckoview

---

grants.yml

tc-admin diff:
```
@@ -124018,25 +124018,33 @@ Role=repo:github.com/mozilla-mobile/mozilla-vpn-client:action:*:
Scopes in this role are defined in [fxci-config/grants.yml](https://github.com/mozilla-releng/fxci-config/blob/main/grants.yml).
scopes:
- docker-worker:cache:mozillavpn-level-3-*
- generic-worker:cache:mozillavpn-level-3-*
- in-tree:hook-action:project-mozillavpn/in-tree-action-3-*
- index:insert-task:mozillavpn.cache.level-3.*
- index:insert-task:mozillavpn.v2.mozilla-vpn-client.*
+      - project:mozillavpn:releng:beetmover:action:import-from-gcs-to-artifact-registry
+      - project:mozillavpn:releng:beetmover:action:push-to-candidates
+      - project:mozillavpn:releng:beetmover:apt-repo:dep
+      - project:mozillavpn:releng:beetmover:bucket:dep
+      - …
```

Bug 1915192 - grant missing scopes to mozilla-vpn-client action tasks

---

clients.yml

list-hooks is granted to anonymous

Remove extra scope from CI client

---

src/ciadmin/generate/in_tree_actions.py

Reasoning is in the comments.
This avoids spurious errors during in tree action generation.

fix: don't try to generate action hooks for private github repositories or globbed projects

---

src/ciadmin/generate/in_tree_actions.py

This used to be the case prior to adding support for multiple branches =\

fix: raise exceptions when a tcyml can't be fetched during action hook generation

---

worker-images.yml

Update windows tester and builder (L1) with taskcluster 68.0.2 + use chocolatey to install updated version of git.

Update windows tester/builder (L1) with tc 68.0.2

---

worker-pools.yml

This config is doing nothing. As far as I can tell, interactive tasks are enabled by default on docker-worker, and there is no limit on maximum run time - so the things that these settings were trying to achieve are already taken care of.

fix: remove unused generic-worker config from translation docker worker pools

---

worker-pools.yml

List spot prices for c2-standard-4 in both us-west1 and us-central1 have been consistently slightly above n2-standard-2 over the last year (e.g. ~13% right now), for twice the CPU/RAM.
Many test tasks running on n2-standard-2 end up CPU bound; switching to c2-standard-4 means 1) twice as many cores, 2) slightly faster cores, which should help both mono- and multi-threaded workloads. Based on an experiment on try, that should be offsetting the cost difference.

Bug 1862675 - switch some gecko linux test pools to c2 instance type

---

.github/workflows/deploy.yml
src/ciadmin/boot.py
src/ciadmin/generate/branches.py
src/ciadmin/generate/in_tree_actions.py

I believe this change is overall a good one, but it has some possibly controversial aspects and/or downsides. I'm interested in any and all feedback or pushback. There might be some ways this can be done without some or all of the downsides.
Most notably, this change more or less requires that a `GITHUB_TOKEN` is set in the environment to run `ci-admin` successfully, otherwise you'll run into rate limits when branches are fetched from Github.
The other, less serious, downside is because we generate hooks for all globbed branches, we end up generating many, many superfluous ones for repos like https://github.com/mozilla/application-services, which have many old and now-unused release branches. One way we could improve this is to _not_ use the `branches` list to determine which branches get …

feat: add support for in tree actions from all configured branches

---

worker-images.yml
worker-pools.yml

Deploys the image created in https://github.com/mozilla-platform-ops/monopacker/pull/146 to an image qualification pool.
- **add new l1 wayland testing image**
- **add pool to use new image being qualified**

add new wayland 2204 image and pool to test it

---

worker-images.yml

Built in https://github.com/mozilla-platform-ops/monopacker/pull/148. 
L1 x86 was promoted to prod in https://github.com/mozilla-releng/fxci-config/pull/100.
Test worker pools: 
- gecko-3/t-linux-2204-wayland-relsre
- gecko-t/t-linux-2204-wayland-arm64-relsre
- gecko-3/t-linux-2204-wayland-arm64-relsre
Testing done: 
- simple tc task, see https://github.com/mozilla-platform-ops/monopacker/pull/148#issuecomment-2364782713
- prod queues lack aliases to target with taskgraph tasks

promote relops1071 arm64 and l3 images

---

grants.yml

Bug 1921006 updates the thunderbird_releng LDAP group to current staff.

Update thunderbird-releng group to use thunderbird_releng LDAP.

---

.github/workflows/deploy.yml

During a recent deploy, we realized that the apply jobs will get cancelled if the other one fails.
This is bad because the apply is not atomic, so if it gets cancelled, it could leave the cluster in a bad state.

ci: ensure apply jobs continue even if the other fails

---

hooks/project-relman/code-coverage-crontrigger-production.yml
hooks/project-relman/code-coverage-crontrigger-testing.yml

These take about a minute, not four hours.
cc @marco-c

hooks: reduce max run time for code-coverage-crontrigger tasks

---

worker-pools.yml

This is needed for `mozilla/fx-desktop-qa-automation` which just transitioned to a level 3 project.
An argument could be made that they should instead get their own trust domain, but personally I feel like *all* projects should be L3. Distinguishing scopes between PRs and pushes is extremely common, even in projects that aren't particularly security sensitive.
Where I think we should draw the line for the `mozilla` trust domain, is if projects start needing scriptworkers for some reason.

fix: create mozilla-3/decision-gcp pool

---

grants.yml

We want to expand the set of developers who can retrigger / cancel / use interactive tasks, etc.. But don't want everyone to be able to read the secrets.
Upon chat with app-services devs who *can* currently see the secrets, they see no need for this ability.

fix: remove secrets:get scope for application-services developers

---

.taskcluster.yml

This will obviously fail to render if any `github-issue-comment` events are processed, but the policy needs to be live on `main` before events will get picked up at all.
So I'm landing only this change for now so I can then work on the other changes in `.taskcluster.yml` that will be needed to make it work.

ci: allow scheduling tasks based on issue comments

---

grants.yml

This is a short term workaround for the fact that we have production tasks that want to use the fake-prod beetmover workers, which are level 1.

grant level 1 scriptworker task creation scopes to level 3 vpn repository

---

grants.yml
projects.yml

This rename is happening in https://github.com/mozilla/firefox-translations-training/pull/914. We plan to land that change and this one around the same time rather than to support both at the same time.

chore: rename production translations repository

---

worker-pools.yml

It looks like we're still OOMing on c2-standard-8.
cc @marco-c

Bug 1919464 - bump code-coverage/bot-gcp instance type to c2-standard-16

---

.taskcluster.yml
grants.yml

This is needed to prevent us from running two Decision tasks on every push / pull-request.

Only use Taskcluster staging instance for pull request comments

---

worker-images.yml
worker-pools.yml

I'm not actively debugging dns stuff for translations; let's remove these for now to avoid confusion.

cleanup: remove unused translations image and pool

---

worker-pools.yml

The existing ones are not used in production, so there's no real risk to doing this.

use new ubuntu 24.04 headless images for d2g translations images

---

taskcluster/kinds/integration/kind.yml

These tasks' definitions get completely overwritten in the `schedule_integration` transforms. The 'dependencies' and 'run' keys here were left over from a previous implementation of the feature that I ended up moving away from.

fix: clean up integration task definitions

---

grants.yml
hooks.yml
hooks/project-relman/code-review-production.yml

This is the same patch as #32 + #39 to enable a new Taskcluster cache `code-review-production-checkout` for the code review production hook (using docker-worker).

Setup checkout cache for code review production hook

---

grants.yml

Refs https://bugzilla.mozilla.org/show_bug.cgi?id=1934254
With this scope, code-review bot developers can retrieve the trigger token  for existing code review hooks so that Phabricator could trigger it.

Allow code-review developers to get the trigger token for their hooks

---

taskcluster/fxci_config_taskgraph/util/integration.py

Due to an oversight on the Gecko side, we accidentally scheduled a Bitbar test. This will be fixed the next time the cron task runs, but this acts as an extra safeguard.

ci: ignore android-hw and macosx integration tests

---

grants.yml

Taskcluster made the pulse messages private by default in https://github.com/taskcluster/taskcluster/pull/7377
This commit adds the newly required scope to keep the current status of it being open

Add the `web:read-pulse` scope to the `anonymous` role

---

grants.yml

https://bugzilla.mozilla.org/show_bug.cgi?id=1935607

Bug 1935607 - cron tasks for automated merge day dry runs fail because a lack of scopes

---

hooks.yml
hooks/project-relman/code-review-testing.yml

Refs https://github.com/mozilla/code-review/issues/2518
The goal of that PR is to support payloads sent by Phabricator webhooks using `triggerHookWithToken` Taskcluster API call, without altering the other triggers (direct & from pulse).
The payload sent by Phabricator is described on [that bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1935142#c6):
```json
{
"object": {
"type": "DREV",
"phid": "PHID-DREV-cljdgxaey4cxvxb4knjp"
},
...
}
```
I only need the object type & phid as environment variables in the created task for now.

Use payload from triggerHookWithToken in code-review-testing hook

---

.github/workflows/deploy.yml

It appears that setting this will cause the 'apply' job to report a successful status even if it failed, which is not what we want.
We want the `notify` job to run regardless of whether its dependencies were successful or not. From the docs, it looks like setting `if: always()` should already accomplish this. Therefore I think it's safe to remove `continue-on-error`.

ci: remove 'continue-on-error' from deploy action

---

taskcluster/fxci_config_taskgraph/transforms/firefoxci_artifact.py
taskcluster/kinds/firefoxci-artifact/kind.yml

I was debating not using the `cached_tasks` transforms and just setting up the index-search optimization manually due to there not being any digest-data.. but I guess this way it'll still work if we ever add any dependencies to these tasks.

ci(integration): turn firefoxci-artifact tasks into cached_tasks

---

.taskcluster.yml
taskcluster/docker/python/Dockerfile

The old version is causing issues in https://github.com/mozilla-releng/fxci-config/pull/210, because `get_ancestors` is not properly memoized.

chore: bump decision task to modern taskgraph version

---

taskcluster/fxci_config_taskgraph/transforms/firefoxci_artifact.py
taskcluster/fxci_config_taskgraph/transforms/integration_test.py

An empty string is not valid JSON:
>>> import json
>>> json.loads("")
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/bhearsum/.pyenv/versions/3.11.6/lib/python3.11/json/__init__.py", line 346, in loads
return _default_decoder.decode(s)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/bhearsum/.pyenv/versions/3.11.6/lib/python3.11/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/bhearsum/.pyenv/versions/3.11.6/lib/python3.11/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

fix: default value for MOZ_FETCHES in integration test transform should be an empty object

---

taskcluster/fxci_config_taskgraph/transforms/firefoxci_artifact.py
taskcluster/fxci_config_taskgraph/transforms/integration_test.py
taskcluster/fxci_config_taskgraph/util/constants.py
taskcluster/fxci_config_taskgraph/util/integration.py
taskcluster/scripts/fetch-firefoxci-artifacts.py
taskcluster/test/test_transforms_firefoxci_artifact.py
taskcluster/test/test_transforms_integration_test.py

This allows them to be imported without depending on any of the imports that `util/integration.py` does. (This is going to become a problem in https://github.com/mozilla-releng/fxci-config/pull/210, when I'm adding a `taskgraph` import there.)

refactor: move taskcluster root url definitions to their own file

---

taskcluster/fxci_config_taskgraph/optimizations.py

This fixes an issue when running the integration-test optimization.

ci: install ci-admin in Decision tasks

---

taskcluster/fxci_config_taskgraph/optimizations.py

tc-admin diff uses the same exit code (1) both for "there was an error" and "I found differences", so its error output is basically the only way we can differentiate currently.

ci: don't hide tc-admin stderr

---

worker-pools.yml

We need to do some additional testing of this with the latest `alpha` image, which requires some new config.

switch translations GPU workers back to alpha image; enable GPUs

---

projects.yml

This is in support of https://bugzilla.mozilla.org/show_bug.cgi?id=1937882, where we'll be adding translations integration tests. A patch for https://github.com/mozilla/translations will follow.

feat: add cron hooks for translations pipeline run

---

worker-pools.yml

This is to work around https://github.com/taskcluster/taskcluster/issues/7423 in a way that doesn't affect actual max run times or cause confusion in the translations repo.

fix: increase max run time for translations worker pools

---

worker-pools.yml

These workers cost slightly more, and have slower downloads due to the Firefox CI GCS buckets being homed in North America. Now that we're not doing large scale training at the moment, we should remove these to ensure that tasks run on North American workers.
cc @gregtatum or @eu9ene for visibility and a sanity check.

bug 1907211: remove europe-west4 from translations worker pools

---

worker-pools.yml

These currently use the default 2 hours, which is very wasteful. 5 minutes ought to be enough for them to reboot and claim another task, if it's available immediately.

lower queue inactivity timeout for expensive translations workers

---

worker-pools.yml

5 minutes causes worker manager to kill the worker. Yarik suggests that the minimum value here should be at least the 20min reclaim period + a 5-10min buffer.

fix: increase queueInActivityTimeout in translations worker pools

---

worker-pools.yml

This was correct, but when we upgraded to the latest image in #252, we picked up a version of generic-worker that requires a slightly different configuration.

fix: use correct configuration for translations cpu workers

---

worker-images.yml
worker-pools.yml

Use a new Ubuntu 22.04 image with a fix for gnome-keyring locking issues.
Based on https://github.com/mozilla-platform-ops/monopacker/pull/153.
see https://mozilla-hub.atlassian.net/browse/RELOPS-1188

RELOPS-1188: add 22.04 image with gnome-keyring fix, use in test pool

---

worker-images.yml

Update image alias to use the latest image built from https://github.com/mozilla-platform-ops/monopacker/pull/153.
See https://mozilla-hub.atlassian.net/browse/RELOPS-1188.

use latest image for monopacker-gw-gcp-wayland-gui-relops1188 alias

---

projects.yml

This will allow testing autograph signing in the staging repo more easily (signing only runs on cron or release tasks in this repo).

fix: add cron hook for staging application services nightly

---

projects.yml

So we can actually run tasks and test things in this repo.

chore: add staging-reference-browser to projects.yml

---

worker-pools.yml

We're seeing widespread `CLAIM_EXPIRED` on these pools which is interfering with ongoing training. I still think we should lower this value, but I'll need to expirement to find a safe value.

fix: drop custom inactivity timeouts for translations workers

---

taskcluster/fxci_config_taskgraph/transforms/firefoxci_artifact.py
taskcluster/fxci_config_taskgraph/transforms/integration_test.py
taskcluster/fxci_config_taskgraph/util/integration.py
taskcluster/kinds/firefoxci-artifact/kind.yml
taskcluster/kinds/integration-test/kind.yml
taskcluster/test/test_transforms_firefoxci_artifact.py
taskcluster/test/test_transforms_integration_test.py

This adds support for running the translations training pipeline as part of integration tests. The first two commits, which add support for fetching upstream tasks that didn't run as part of a decision task and support for rewriting dependencies to the yet-to-be-scheduled tasks are the interesting parts. The other few commits are pretty boring, and simply fix a minor bug and enable the translations tests.
Note that these depends on https://github.com/mozilla-releng/fxci-config/pull/228, a yet to be opened PR in https://github.com/mozilla/translations to add a pipeline cronjob. It's currently running against the staging repository and working well though.

feat: translations integration tests

---

worker-pools.yml

Generic Worker's config `d2gConfig.containerEngine` will be removed soon with https://github.com/taskcluster/taskcluster/pull/7482.
This change is safe to land now, as `docker` is the default, anyway.

chore: remove `containerEngine` config

---

hooks.yml
hooks/project-relman/code-review-testing.yml

This PR simplifies the payload required to trigger the hook with a token, as Phabricator will now directly call `triggerHookWithToken` and provides the build target PHID (instead of the webhook trigger payload).
The build plan is pending deployment on phabricator-dev: https://bugzilla.mozilla.org/show_bug.cgi?id=1935142#c24
A PR is also pending review on the bot to support the new environment variable https://github.com/mozilla/code-review/pull/2611/

Use Phabricator build target PHID when triggering code-review hook

---

clients-interpreted.yml
projects.yml

Note that this is getting added in `clients-interpreted.yml` for Gecko, which is something we haven't done up until now. I have mixed feelings about this as these clients are shared across multiple projects, but I _think_ having consistency in the client entries is worthwhile.

feat: add lando scriptworker client for dev

---

clients.yml

I’m familiar with creating worker pools like this:
```
project/releng/generic-worker/datacenter-gecko-t-osx-1400-r8:
description: Datacenter MacOS dedicated developer and automation worker.
scopes:
- assume:worker-type:releng-hardware/gecko-t-osx*
- queue:worker-id:mdc1/mac*
```
However, setting up the new Mac hardware signing machines is a bit more of a mystery to me.
For reference, the current M2 Mac signing hardware designated for this purpose is named something like this (though this can change)
`macmini-m2-44.test.releng.mdc1.mozilla.com`
The goal—perhaps obvious—is to spin up a new Firefox production signing pool on ARM/macOS 14.
Would love any feedback or insights! 😊
Existing signer [pools](https://firefox-ci-tc.services.mozilla.com/provisioners/scriptworker-prov-v1/worker-types/) …

[RELOPS-773] Provision new Mac Signers

---

taskcluster/kinds/firefoxci-artifact/kind.yml
taskcluster/kinds/integration-test/kind.yml

These tasks changed names when Translations picked up a new Taskgraph version. At the moment we're in a state where both are present in the most recent cron run (some docker images have been rebuilt, others haven't); we need to keep both in here for awhile to avoid accidentally trying to rebuild them in staging (which doesn't work, and is wasteful).
This should fix the issue with integration tests I noticed in #292.

fix: ignore new and old names for docker image tasks in translations integration tests

---

worker-images.yml

The main change here is generic-worker 81.0.3, which includes interactive task improvements and chain of trust d2g fixes compared to the current image.

chore: pick up new ubuntu 24.04 headless image

---

worker-pools.yml

And also, use the newly minted dated image for them, which appears to be working well in https://github.com/mozilla/translations/pull/700.

bug 1904569: add remaining d2g-enabled worker pools for translations GPU workers

---

clients.yml

I’ve made progress in automating the signer and tester [images](https://github.com/rcurranmoz/macos-image-templates/tree/master/moz/tester), and they are now mostly functional. I’d like to set up two pools for macOS 14/15 VMs to run in. For now, I’ve removed the M2/M4 designation since these VMs are provisioned with minimal resources and may be deployed interchangeably on M2 and M4 hardware.

Edit mac vm pools

---

grants.yml

This is mainly to allow them to more easily test things on Try, although it technically allows it on certain other repositories as well.

feat: grant merge-automation action scopes to L1 users

---

hooks.yml
hooks/project-relman/code-review-production.yml

This is the same work as #278 but for the production hook.
We want to try out the new code-review trigger system in production soon.

Use Phabricator build target PHID when triggering code-review production hook

---

worker-pools.yml

10 workers isn't enough to get through a full try push in reasonable time.

gecko-t/t-linux-2404-headless-alpha: bump maxCapacity

---

clients.yml
grants.yml

Switching it to prefix `dep-` so it matches old configs and renames the tb workers to use the trust domain (comm) instead of just tb

[RELOPS-773] Update m2 Mac signers scopes + missing grants + comm vs tb 

---

src/ciadmin/generate/worker_pools.py

In https://github.com/mozilla-releng/fxci-config/pull/317 we noticed some seemingly unrelated changes to worker pools in a taskgraph diff. This is almost certainly because we're not sorting regions/AZs/instance types when generating these.
It's difficult to fully verify this, but I did manage to get three identical diffs locally with this patch, and the minimal diff (ie: no additions/removals from reordering) when making a minor change to a worker pool.

fix: make worker pool generation deterministic

---

clients.yml

See https://mozilla-hub.atlassian.net/browse/RELOPS-1356.
Create a production/non-testing client.

RELOPS-1356: add perf-a55 lambdatest client

---

worker-images.yml

This moves us from 81.0.3 to 83.4.0, most notably picking up the new `volume` artifact type (https://github.com/taskcluster/taskcluster/issues/7594) and OOM monitoring (https://github.com/taskcluster/taskcluster/issues/6464).
The former is a blocking issues for moving translations GPU workers over to this image.

chore: bump ubuntu headless 24.04 image to pick up new generic-worker version

---

projects.yml

Similar to what the android repo used to have (16e89a0938e3bf096507ec4c1e39d98fd24273fb)

Add github publication scopes to ios repos

---

worker-pools.yml

Let's make sure we can test the -alpha image on these workloads.

Bug 1962416 - add gecko-t/t-linux-docker-kvm-alpha worker pool

---

worker-pools.yml

Fixes:
`Invalid value for field
'resource.disks[0].initializeParams.diskSizeGb': '20'.  Requested disk size cannot be smaller than the image size (60 GB)`

Bump boot disk size for b-linux-docker-alpha (bug 1959596)

---

projects.yml

I learned yesterday that these are not what I thought they were. The new names match what is in https://phabricator.services.mozilla.com/diffusion/ (`firefox-main` doesn't exist yet, but it will in the near future).

fix: update lando repo names to match reality

---

cron-task-template.yml
hg-push-template.yml

This is mostly to pick 410dfc7d9bd24da65800a914fc6faeb5ab1571cf up to avoid unauthenticated calls to the github API as it leads to exceeding rate limits very easily.

Update build-decision image

---

grants.yml

When index entries are added by an index-task instead of directly via routes on the task itself (as happens when the task has more than 10 routes), that index-task needs the index:insert-task scope.

Bug 1964918 - add missing scope for index-tasks on "trunk"

---

grants.yml

We're switching to the repositories being created in https://github.com/mozilla-conduit/lando/pull/316, which will allow us to have a RelEng controlled repository hooked up to stage Lando.

fix(landoscript): grant try scopes for all staging-* lando repositories

---

grants.yml

Ought to have been done in https://github.com/mozilla-releng/fxci-config/pull/359, but I missed it.

bug 1965417: fix landoscript repo scope for merge day dry runs

---

worker-images.yml

This will pick up https://github.com/mozilla-platform-ops/worker-images/pull/293, which picks up a new generic-worker version that is expected to fix https://github.com/mozilla/translations/issues/1117#issuecomment-2880387322.

chore: bump ubuntu 24.04 headless image.

---

src/ciadmin/generate/tcyml.py

When I added support for fetching these with a GITHUB_TOKEN in #381 I failed to realize that with the revision now not included in the cache key, we have race conditions / collisions, which results in some hooks not being generated.

bug 1966916: fix: cache key when fetching tcyml files

---

projects.yml

Need this to be able to test automating beta releases

Add the required config to run cronjob on the firefox ios repo

---

clients.yml

I'm not sure this is correct, I don't understand why we have to have 3 of the same scopes (no prefix/dev/staging) but that seems to be what other shipit dev workers do 🤷

Add scopes to create ios releases on mobile-1-dev shipit scriptworker

---

worker-pools.yml

While I'm there, remove the minCapacity so we don't keep one idle worker running all the time.

Bug 1925873 - bump code-coverage/bot-gcp pool to c2-standard-30

---

worker-pools.yml

grcov is currently OOMing even with 120G, so get back to a reasonably sized instance assuming that when we update grcov it won't need silly amounts of memory anymore.

Bug 1925873 - switch code-coverage/bot-gcp pool back to c2-standard-4

---

grants.yml

This was replaced in https://bugzilla.mozilla.org/show_bug.cgi?id=1967638

chore: remove last remnant of central-to-beta name

---

worker-pools.yml

Issues creating VMs here https://firefox-ci-tc.services.mozilla.com/worker-manager/translations-1%2Fb-linux-v100-gpu-d2g-1tb-alpha/errors

fix: use 4 gpus for translations alpha pool

---

clients.yml
grants.yml
projects.yml

This is a basically 8aceceb2d43a04a492d4adfd8263d4eb362d4df2, 22790145b650633e6c4e4d24c9e4569309fee097 and
0239d534afe83704fc1adb1e45d95e9b75546469 but for firefox-ios instead of staging-firefox-ios and targeting shipit prod

Add the required scopes and hooks for firefox ios to run automated betas

---

hooks/project-relman/code-review-testing.yml

Followup #403
The [code-review-testing hook](https://firefox-ci-tc.services.mozilla.com/hooks/project-relman/code-review-testing) has been updated with the changes from #403, but all the trigerred tasks now fail with that error:
```
TemplateError at template.payload.env[2]: $if can evaluate string expressions only
```

Remove $eval in $if condition for code-review testing hook

---

grants.yml
projects.yml

This reverts commit 7b9591d410c9136247dbce9332282dc4cb7ae0d7.
I got a bit eager at merging this, ended up merging it too early which means that cronjobs are now running with an empty pushlog and crashing. And I can't push to the esr140 branch because the lando work hasn't been done yet

Revert "Bug 1964711 - Add mozilla-esr140 configuration and scopes (#410)

---

worker-pools.yml

I have a task that seems to hit this, I would like to test on try if it passes consistently with the check turned off.

Disable generic-worker OOM protection for t-linux-2404-headless-ssd-alpha

---

hooks.yml
hooks/project-relman/code-review-production.yml

This is the same patch as #403 + #413 for code-review production hook.
---
Refs https://github.com/mozilla/code-review/pull/2801 & https://github.com/mozilla/code-review/issues/2773
The code-review hook must support pulse message triggers sent at the end of Mozilla Central & Autoland build groups.
We already did that by using the [events sub-system](https://github.com/mozilla/code-review/blob/95b29a76006f7c5462a7c096a95055b3b978ed33/events/code_review_events/workflow.py#L404), but now we only use the bot through its hook.
The hook will now have 2 pulse triggers:
1. from try pushes, transforming the payload into `TRY_RUN_ID`, `TRY_TASK_GROUP_ID` and `TRY_TASK_ID` environment variables
2. from Autoland / MC groups, transforming the payload into a unique `GENERIC_TASK_GROUP_ID`

Support Autoland or Mozilla-Central pulse trigger for code-review production hook

---

worker-pools.yml

Reverts mozilla-releng/fxci-config#419
https://github.com/taskcluster/taskcluster/pull/7775 lets us tweak the OOM detection parameters.

Revert "Disable generic-worker OOM protection for t-linux-2404-headless-ssd-alpha"

---

build-decision/src/build_decision/cron/__init__.py
build-decision/src/build_decision/repository.py
build-decision/tests/test_cron.py
build-decision/tests/test_repository.py

This seems to be a footgun when setting up a new repository: you can't add it to fxci-config until you push to it, which is both unintuitive, and seems less than ideal (any push you make wouldn't have jobs run, i think?).
Theoretically this could happen if there's an issue on hg.m.o, but I'm not sure that's worth worrying about.

feat: don't fail cron runs when pushlog is empty

---

grants.yml

Here's the tc-admin diff:
```diff
--- current
+++ generated
@@ -314715,32 +314715,42 @@ Role=repo:github.com/mozilla-platform-ops/worker-images:pr-action:*:
Role=repo:github.com/mozilla-platform-ops/worker-images:pull-request:
roleId: repo:github.com/mozilla-platform-ops/worker-images:pull-request
description:
*DO NOT EDIT* - This resource is configured automatically by [ci-admin](https://github.com/mozilla-releng/fxci-config).
Scopes in this role are defined in [fxci-config/grants.yml](https://github.com/mozilla-releng/fxci-config/blob/main/grants.yml).
scopes:
+      - assume:repo:github.com/mozilla/translations:action:train
- docker-worker:cache:relops-level-1-*
- docker-worker:cache:relops-project-worker-images-level-1-*
+      - docker-worker:capability:device:kvm
+      - …
```

Bug 1976483 - Grant os-integration scopes to worker-images repo

---

projects.yml

These fail sometimes, and it can be useful to run them again by hand.

feat: generate cron hook for os-integration tests

---

.github/workflows/deploy.yml

I think this is all that's needed...
But it's hard to test because it needs to exist on the default branch first.

ci: allow manually triggering the 'deploy' action

---

projects.yml

This target is going to be triggered during the image deploy pipeline (which is in GH Actions). So the GH Action workflow will pass in the name of the image being deployed, which will then be used during Taskgraph's optimization phase to only run relevant tasks.

fix: allow input in worker-image's 'run-integration-tests' target

---

build-decision/src/build_decision/cron/decision.py
build-decision/src/build_decision/hg_push.py
build-decision/tests/test_cron_decision.py
build-decision/tests/test_hg_push.py

The Taskcluster Github service renders .taskcluster.yml with a `taskcluster_root_url` context. We started relying on this in fxci-config as part of the integration test changes.
However, this broke the `test-build-decision` cron hook, which *doesn't* render .taskcluster.yml with `taskcluster_root_url`. We could simply update our `.taskcluster.yml` to check if the context exists before using it, but IMO we should make the context between the two places (Github service and build-decision) as close to each other as possible.
So let's ensure we're passing `taskcluster_root_url` as context.

fix: add 'taskcluster_root_url' to build-decision render context

---

cron-task-template.yml
hg-push-template.yml

This is to pick up a new feature allowing cron decision tasks to use hook input.

chore: update build-decision to latest image

---

worker-pools.yml

For some reason GCP doesn't have c3d-standard-4-lssd instances

fix: c3d lssd instances with 4->8 cores

---

worker-pools.yml

This is needed to run `tgdiff` without OOMing after adding multiprocess support.

feat: add xlarge pool for t-linux-docker

---

src/ciadmin/check/check_privileged.py

By looking at the raw worker-pools without resolving variants, we ended up with an empty list of trusted pools, and therefore weren't checking anything.

ciadmin: fix privileged check's list of trusted pools

---

worker-pools.yml

Right now c3d instances are available, but not with lssd. I'm just removing the region for now, and will implement a better system to add lssd to invalid-instances config

Fix(worker-pools): Remove us-west1 from c3d pools

---

taskcluster/kinds/firefoxci-artifact/kind.yml
taskcluster/kinds/integration-test/kind.yml

`mochitest` was split out of the catch-all `test` kind.

Bug 1990017 - add mochitest kind to gecko integration tests

---

src/ciadmin/check/check_privileged.py
worker-pools.yml

As far as I can tell this is only used by get_aws_provider_config, so was presumably just copied over during the migration to gcp.

Remove unused `security` from pool configs

---

worker-pools.yml

While looking at the pending times dashboard, I noticed we are waiting an average of nearly 2 hours for tasks on this pool.

fix: bump max capacity for `gecko-2/b-linux-medium-gcp`

---

worker-images.yml

Reverts mozilla-releng/fxci-config#542 due to https://github.com/mozilla/translations/issues/1266.

Revert "chore(feature): update 24.04 ubuntu images with latest tc binaries"

---

worker-pools.yml

I added a new region for these in https://github.com/mozilla-releng/fxci-config/pull/567; we should probably raise the max capacity as well. (It's unclear to me why we'd want `gecko-3` to be lower capacity than `gecko-1`, so I'm raising it to match that.)

raise maxCapacity to 200 for `b-linux-medium-gcp`

---

clients.yml
projects.yml

While looking at adding more scopes I got confused as to why we only had gecko/comm/mobile in the list of scopes added to the shipit clients. Turns out that those scopes are inferred for other projects using the `shipit` feature. gecko/comm are the only trust domains that did not have a single project with the shipit feature, the mobile scopes were useless. I ended up marking all gecko/comm branches interacting with shipit with the feature (technically we only need on project per trust domain/level but I wanted to avoid the confusion).
The only resulting changes are the description of the clients and that it's going to create a comm-1-dev client.

Use the shipit project feature rather than giving scopes manually to shipit
