mozilla-releng/fxci-config

.github/CODEOWNERS
We make changes to this file for static/standalone clients relatively often.
=> add relops to codeowners for clients.yml

.taskcluster.yml, taskcluster/config.yml, taskcluster/kinds/docker-image/kind.yml, taskcluster/kinds/tests/kind.yml
This is currently breaking PRs; fallout from #22.
=> fix: get rid of treeherder references in .taskcluster.yml/taskcluster directory

src/ciadmin/generate/in_tree_actions.py
Switching from `asyncio.gather` to individual `awaits` added a ton of overhead. Restoring `gather` usage required some refactoring, so I've split it out for easier reviewing.
Already reviewed in https://phabricator.services.mozilla.com/D216207
=> Bug 1907169: improve regression in in_tree_action performance

environments.yml, worker-pools.yml
Let's see how these perform, and the actual costs we pay for them vs. North America ones.
=> bug 1907211: add a single translations GPU worker in europe as a trial

.gitignore
https://moz-releng-docs.readthedocs.io/en/latest/how-to/taskcluster/ci_admin.html#run
=> Ignore files generated when running ci-admin as per docs

src/ciadmin/check/check_grants.py
The current logic is not quite correct, but it didn't come up until I opened https://github.com/mozilla-releng/fxci-config/pull/46.
=> fix: make check_insecure_grants aware of multiple branches per project

clients.yml
https://mozilla-hub.atlassian.net/browse/RELOPS-721
=> Add clients for new Mozilla trust domain pool

clients.yml
https://mozilla-hub.atlassian.net/browse/RELOPS-721
=> [RELOPS-721] Added new scope to accomodate new pool name

projects.yml
This repository was archived in April of 2023.
=> chore: remove rally-core-addon from projects.yml

projects.yml
A few small tweaks here to reflect reality.
=> fix: sync up projects.yml with reality

src/ciadmin/generate/in_tree_actions.py
This makes diffs more readable.
=> fix: use deterministic sorting for in tree action descriptions

worker-images.yml, worker-pools.yml
=> remove aerickson translations test pool

worker-images.yml
Image looks good, promote to prod.
Test notes in https://bugzilla.mozilla.org/show_bug.cgi?id=1914495.
=> promote monopacker-gw-gcp-wayland-gui-relops1071 l1 image to prod

worker-images.yml, worker-pools.yml
More work related to https://bugzilla.mozilla.org/show_bug.cgi?id=1914495.
- **add l3 x86 and l1 and l3 arm64 images**
- **add new worker pools to test new images added**
=> setup test pools for images 091924

worker-images.yml, worker-pools.yml
Related to https://github.com/mozilla-platform-ops/monopacker/pull/149 and https://github.com/mozilla/firefox-translations-training/issues/549
=> add test image for translations worker with dnsmasq instead of system-resolved

build-decision/src/build_decision/repository.py, build-decision/tests/test_repository.py
The private repository stuff was already implemented in the path to get push info but not in the `get_file` method.
=> Allow build-decision to get files from private github repositories

clients.yml, worker-pools.yml
This project doesn't exist anymore and the hardware has been decomissioned.
=> Bug 1922045 - Remove worker pool for desktop recorder project

clients.yml
Per [RELOPS-1143](https://mozilla-hub.atlassian.net/browse/RELOPS-1143)
=> Add m4 staging pool

clients.yml
https://bugzilla.mozilla.org/show_bug.cgi?id=1927416
=> Add temporary r8 pool for debugging

.github/workflows/deploy.yml, grants.yml, taskcluster/config.yml, taskcluster/fxci_config_taskgraph/__init__.py, taskcluster/fxci_config_taskgraph/target_tasks.py, taskcluster/kinds/tc-admin/kind.yml, taskcluster/scripts/tc-admin-apply-staging.py
This can be done by commenting `/taskcluster apply-staging`
=> Add ability to deploy pull requests to the Taskcluster staging instance

src/ciadmin/generate/worker_pools.py, src/ciadmin/util/keyed_by.py, worker-pools.yml
This makes heavier use of variants to reduce duplication in the Windows configs.
=> Consolidate Windows worker-pool configuration

clients.yml
https://mozilla-hub.atlassian.net/browse/RELOPS-1148
=> [RELOPS-1148] Add macOS 14 r8 prod pool

grants.yml, hooks.yml, hooks/project-relman/code-review-production.yml
According to @Archaeopteryx:
> It causes issues (every exist detected by reviewbot gets reported as new, even preexisting ones)
=> revert #159

grants.yml, hooks.yml, hooks/project-relman/code-review-production.yml
This is a reland of #159 after the project's configuration got adjusted for this change.
=> Setup checkout cache for code review production hook

hooks.yml
=> hooks: fix project-relman/code-review-testing trigger schema

taskcluster/fxci_config_taskgraph/__init__.py, taskcluster/fxci_config_taskgraph/optimizations.py, taskcluster/fxci_config_taskgraph/transforms/integration_test.py, taskcluster/test/test_optimizations.py, taskcluster/test/test_transforms_integration_test.py
This ensures we only schedule the integration tests that are relevant to the PR at hand.
=> ci: implement an optimization for the integration tests

worker-pools.yml
generic-worker v77 moved enableD2G under d2gConfig.
=> Update d2g config for gecko ubuntu24.04 alpha pools

projects.yml
=> Update the staging-firefox-ios repo path

.taskcluster.yml
=> chore: bump taskgraph in .taskcluster.yml

taskcluster/fxci_config_taskgraph/transforms/integration_test.py
=> ci: always re-write scopes for integration tests

src/ciadmin/generate/worker_pools.py, tests/ciadmin/test_generate_worker_pools.py, worker-pools.yml
Similar to https://github.com/taskcluster/community-tc-config/pull/922.
Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1952309.
=> chore: adjust worker pool generation based on new launch config changes

grants.yml
Those workflows run from actions, not from pushes to branches
=> Grant release promotion workflows to action:release-promotion for fxios

projects.yml
Similar to what was done for android here: 7476ba819d05e9772d1ead1885e10a95344874d2
=> Add treescript scopes for fxios repos

clients.yml
https://mozilla-hub.atlassian.net/browse/RELOPS-1413
New M4s will be ready in MacStadium tomorrow. We already have a staging client. Added a prod client.
=> [RELOPS-1413] Add M4 pool

clients.yml
=> Remove mac14 vm client

clients.yml
https://mozilla-hub.atlassian.net/browse/RELOPS-1454
=> [RELOPS-1454] decom -latest mac pools

worker-pools.yml
=> Bump maxCapacity for gecko-t/t-linux-docker-kvm

src/ciadmin/generate/tcyml.py
This _should_ fix the staging apply in os-integration tests.
=> bug 1967745: feat: support public, token, and app clients in tcyml.py for github repositories

projects.yml
I meant to do this in #434 but modified comm-esr115 instead :facepalm:
=> Turn off cron for comm-esr140 for real

clients.yml
See https://mozilla-hub.atlassian.net/browse/RELOPS-1636.
=> RELOPS-1636: add client for lambdatest pixel 9s

clients.yml
See https://mozilla-hub.atlassian.net/browse/RELOPS-1903.
=> RELOPS-1903: add project/relsre/devicepool tc client
